### ISSUE TITLE
atomicswap build error 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_builders#15] opened 2019-09-08 08:59 UTC
- atomicswap build error 

![ff](https://user-images.githubusercontent.com/21218053/64485998-c01a0900-d227-11e9-86de-130fef2aee9b.png)

**Comment by rkhamis** [comment] 2020-03-17 09:08
duplicate of https://github.com/threefoldtech/jumpscaleX_builders/issues/18

**Closed as completed by rkhamis** 2020-03-17 09:08 UTC
Labels: type_bug
